// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID       uuid.UUID      `json:"id"`
	Name     string         `json:"name"`
	Username string         `json:"username"`
	Email    sql.NullString `json:"email"`
	Password string         `json:"password"`
}
